CREATE SCHEMA IF NOT EXISTS product;
CREATE SCHEMA IF NOT EXISTS capability;
CREATE SCHEMA IF NOT EXISTS user_auth;
CREATE SCHEMA IF NOT EXISTS techradar;
CREATE SCHEMA IF NOT EXISTS pack_loader;
CREATE SCHEMA IF NOT EXISTS entity_events;

DO $$
BEGIN
    RAISE NOTICE 'Schemas created successfully';
END $$;